//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SKV.PL.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, подтвердите выполнение действия!.
        /// </summary>
        public static string ActionConfirmation {
            get {
                return ResourceManager.GetString("ActionConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действия.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администрирование.
        /// </summary>
        public static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет об отмененных заказах.
        /// </summary>
        public static string CanceledOrdersReport {
            get {
                return ResourceManager.GetString("CanceledOrdersReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет об остатках ДС.
        /// </summary>
        public static string CashRemainsReport {
            get {
                return ResourceManager.GetString("CashRemainsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Корректировка.
        /// </summary>
        public static string Correction {
            get {
                return ResourceManager.GetString("Correction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет о проведённы сделках.
        /// </summary>
        public static string DealReport {
            get {
                return ResourceManager.GetString("DealReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эл. почта.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Журнал событий.
        /// </summary>
        public static string EventJournal {
            get {
                return ResourceManager.GetString("EventJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обмен.
        /// </summary>
        public static string Exchange {
            get {
                return ResourceManager.GetString("Exchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ид.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инвентаризация.
        /// </summary>
        public static string Inventarisation {
            get {
                return ResourceManager.GetString("Inventarisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет о соответсвии ДС.
        /// </summary>
        public static string InventarisationReport {
            get {
                return ResourceManager.GetString("InventarisationReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя или пароль указаны неверно!.
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход выполнен.
        /// </summary>
        public static string LoginSuccessfull {
            get {
                return ResourceManager.GetString("LoginSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход в систему.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройка меню.
        /// </summary>
        public static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кассовые операции.
        /// </summary>
        public static string MoneyTransfer {
            get {
                return ResourceManager.GetString("MoneyTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Система мониторинга.
        /// </summary>
        public static string MonitoringSystem {
            get {
                return ResourceManager.GetString("MonitoringSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оператор.
        /// </summary>
        public static string Operator {
            get {
                return ResourceManager.GetString("Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Смена пароля.
        /// </summary>
        public static string PasswordChanging {
            get {
                return ResourceManager.GetString("PasswordChanging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль успешно изменен!.
        /// </summary>
        public static string PasswordChangingSuccess {
            get {
                return ResourceManager.GetString("PasswordChangingSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер телефона.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет о прибыли.
        /// </summary>
        public static string ProfitReport {
            get {
                return ResourceManager.GetString("ProfitReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчеты.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Менеджер ролей.
        /// </summary>
        public static string RoleManager {
            get {
                return ResourceManager.GetString("RoleManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основные настройки.
        /// </summary>
        public static string RoleProfileMainPropertiesTab {
            get {
                return ResourceManager.GetString("RoleProfileMainPropertiesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разрешения.
        /// </summary>
        public static string RoleProfilePermissionsTab {
            get {
                return ResourceManager.GetString("RoleProfilePermissionsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка системы.
        /// </summary>
        public static string SystemLoading {
            get {
                return ResourceManager.GetString("SystemLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки системы.
        /// </summary>
        public static string SystemSettings {
            get {
                return ResourceManager.GetString("SystemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес электронной почты.
        /// </summary>
        public static string User_Email {
            get {
                return ResourceManager.GetString("User.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string User_PhoneNumber {
            get {
                return ResourceManager.GetString("User.PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уникальный номер в системе Asterisk.
        /// </summary>
        public static string User_Profile_AsteriskId {
            get {
                return ResourceManager.GetString("User.Profile.AsteriskId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инициалы.
        /// </summary>
        public static string User_Profile_Name {
            get {
                return ResourceManager.GetString("User.Profile.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роли.
        /// </summary>
        public static string User_Roles {
            get {
                return ResourceManager.GetString("User.Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин.
        /// </summary>
        public static string User_UserName {
            get {
                return ResourceManager.GetString("User.UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание пользователя.
        /// </summary>
        public static string UserCreating {
            get {
                return ResourceManager.GetString("UserCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идентификатор в системе Asterisk.
        /// </summary>
        public static string UserCreatingViewModel_AsteriskId {
            get {
                return ResourceManager.GetString("UserCreatingViewModel.AsteriskId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение пароля.
        /// </summary>
        public static string UserCreatingViewModel_ConfirmPassword {
            get {
                return ResourceManager.GetString("UserCreatingViewModel.ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес электронной почты.
        /// </summary>
        public static string UserCreatingViewModel_Email {
            get {
                return ResourceManager.GetString("UserCreatingViewModel.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инициалы.
        /// </summary>
        public static string UserCreatingViewModel_Initials {
            get {
                return ResourceManager.GetString("UserCreatingViewModel.Initials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string UserCreatingViewModel_Password {
            get {
                return ResourceManager.GetString("UserCreatingViewModel.Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер телефона.
        /// </summary>
        public static string UserCreatingViewModel_PhoneNumber {
            get {
                return ResourceManager.GetString("UserCreatingViewModel.PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роли.
        /// </summary>
        public static string UserCreatingViewModel_Roles {
            get {
                return ResourceManager.GetString("UserCreatingViewModel.Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин.
        /// </summary>
        public static string UserCreatingViewModel_UserName {
            get {
                return ResourceManager.GetString("UserCreatingViewModel.UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инициалы.
        /// </summary>
        public static string UserInitials {
            get {
                return ResourceManager.GetString("UserInitials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Менеджер пользователей.
        /// </summary>
        public static string UserManager {
            get {
                return ResourceManager.GetString("UserManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый пароль.
        /// </summary>
        public static string UserPasswordChangingViewModel_NewPassword {
            get {
                return ResourceManager.GetString("UserPasswordChangingViewModel.NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение нового пароля.
        /// </summary>
        public static string UserPasswordChangingViewModel_NewPasswordConfirm {
            get {
                return ResourceManager.GetString("UserPasswordChangingViewModel.NewPasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старый пароль.
        /// </summary>
        public static string UserPasswordChangingViewModel_OldPassword {
            get {
                return ResourceManager.GetString("UserPasswordChangingViewModel.OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль пользователя.
        /// </summary>
        public static string UserProfile {
            get {
                return ResourceManager.GetString("UserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование.
        /// </summary>
        public static string UserRole_Name {
            get {
                return ResourceManager.GetString("UserRole.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование страницы по умолчанию.
        /// </summary>
        public static string UserRole_PageInstance_Name {
            get {
                return ResourceManager.GetString("UserRole.PageInstance.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL страницы по умолчанию.
        /// </summary>
        public static string UserRole_PageInstance_URL {
            get {
                return ResourceManager.GetString("UserRole.PageInstance.URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отображаемая при входе страница.
        /// </summary>
        public static string UserRole_Pages {
            get {
                return ResourceManager.GetString("UserRole.Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разрешения.
        /// </summary>
        public static string UserRole_Permissions {
            get {
                return ResourceManager.GetString("UserRole.Permissions", resourceCulture);
            }
        }
    }
}
