//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SKV.PL.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста, подтвердите выполнение действия!.
        /// </summary>
        public static string ActionConfirmation {
            get {
                return ResourceManager.GetString("ActionConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Действия.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Администрирование.
        /// </summary>
        public static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчет об отмененных заказах.
        /// </summary>
        public static string CanceledOrdersReport {
            get {
                return ResourceManager.GetString("CanceledOrdersReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчет об остатках ДС.
        /// </summary>
        public static string CashRemainsReport {
            get {
                return ResourceManager.GetString("CashRemainsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Корректировка.
        /// </summary>
        public static string Correction {
            get {
                return ResourceManager.GetString("Correction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчет о проведённы сделках.
        /// </summary>
        public static string DealReport {
            get {
                return ResourceManager.GetString("DealReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Эл. почта.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Журнал событий.
        /// </summary>
        public static string EventJournal {
            get {
                return ResourceManager.GetString("EventJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обмен.
        /// </summary>
        public static string Exchange {
            get {
                return ResourceManager.GetString("Exchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ид.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инвентаризация.
        /// </summary>
        public static string Inventarisation {
            get {
                return ResourceManager.GetString("Inventarisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчет о соответсвии ДС.
        /// </summary>
        public static string InventarisationReport {
            get {
                return ResourceManager.GetString("InventarisationReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя пользователя.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Войти.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя пользователя или пароль указаны неверно!.
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вход выполнен.
        /// </summary>
        public static string LoginSuccessfull {
            get {
                return ResourceManager.GetString("LoginSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вход в систему.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройка меню.
        /// </summary>
        public static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кассовые операции.
        /// </summary>
        public static string MoneyTransfer {
            get {
                return ResourceManager.GetString("MoneyTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Система мониторинга.
        /// </summary>
        public static string MonitoringSystem {
            get {
                return ResourceManager.GetString("MonitoringSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оператор.
        /// </summary>
        public static string Operator {
            get {
                return ResourceManager.GetString("Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Смена пароля.
        /// </summary>
        public static string PasswordChanging {
            get {
                return ResourceManager.GetString("PasswordChanging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль успешно изменен!.
        /// </summary>
        public static string PasswordChangingSuccess {
            get {
                return ResourceManager.GetString("PasswordChangingSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер телефона.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчет о прибыли.
        /// </summary>
        public static string ProfitReport {
            get {
                return ResourceManager.GetString("ProfitReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчеты.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Менеджер ролей.
        /// </summary>
        public static string RoleManager {
            get {
                return ResourceManager.GetString("RoleManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка системы.
        /// </summary>
        public static string SystemLoading {
            get {
                return ResourceManager.GetString("SystemLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки системы.
        /// </summary>
        public static string SystemSettings {
            get {
                return ResourceManager.GetString("SystemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес электронной почты.
        /// </summary>
        public static string User_Email {
            get {
                return ResourceManager.GetString("User.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Телефон.
        /// </summary>
        public static string User_PhoneNumber {
            get {
                return ResourceManager.GetString("User.PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уникальный номер в системе Asterisk.
        /// </summary>
        public static string User_Profile_AsteriskId {
            get {
                return ResourceManager.GetString("User.Profile.AsteriskId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инициалы.
        /// </summary>
        public static string User_Profile_Name {
            get {
                return ResourceManager.GetString("User.Profile.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Роли.
        /// </summary>
        public static string User_Roles {
            get {
                return ResourceManager.GetString("User.Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логин.
        /// </summary>
        public static string User_UserName {
            get {
                return ResourceManager.GetString("User.UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создание пользователя.
        /// </summary>
        public static string UserCreating {
            get {
                return ResourceManager.GetString("UserCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Идентификатор в системе Asterisk.
        /// </summary>
        public static string UserCreatingViewModel_AsteriskId {
            get {
                return ResourceManager.GetString("UserCreatingViewModel.AsteriskId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтверждение пароля.
        /// </summary>
        public static string UserCreatingViewModel_ConfirmPassword {
            get {
                return ResourceManager.GetString("UserCreatingViewModel.ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес электронной почты.
        /// </summary>
        public static string UserCreatingViewModel_Email {
            get {
                return ResourceManager.GetString("UserCreatingViewModel.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инициалы.
        /// </summary>
        public static string UserCreatingViewModel_Initials {
            get {
                return ResourceManager.GetString("UserCreatingViewModel.Initials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        public static string UserCreatingViewModel_Password {
            get {
                return ResourceManager.GetString("UserCreatingViewModel.Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер телефона.
        /// </summary>
        public static string UserCreatingViewModel_PhoneNumber {
            get {
                return ResourceManager.GetString("UserCreatingViewModel.PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Роли.
        /// </summary>
        public static string UserCreatingViewModel_Roles {
            get {
                return ResourceManager.GetString("UserCreatingViewModel.Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логин.
        /// </summary>
        public static string UserCreatingViewModel_UserName {
            get {
                return ResourceManager.GetString("UserCreatingViewModel.UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инициалы.
        /// </summary>
        public static string UserInitials {
            get {
                return ResourceManager.GetString("UserInitials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Менеджер пользователей.
        /// </summary>
        public static string UserManager {
            get {
                return ResourceManager.GetString("UserManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логин.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый пароль.
        /// </summary>
        public static string UserPasswordChangingViewModel_NewPassword {
            get {
                return ResourceManager.GetString("UserPasswordChangingViewModel.NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтверждение нового пароля.
        /// </summary>
        public static string UserPasswordChangingViewModel_NewPasswordConfirm {
            get {
                return ResourceManager.GetString("UserPasswordChangingViewModel.NewPasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Старый пароль.
        /// </summary>
        public static string UserPasswordChangingViewModel_OldPassword {
            get {
                return ResourceManager.GetString("UserPasswordChangingViewModel.OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Профиль пользователя.
        /// </summary>
        public static string UserProfile {
            get {
                return ResourceManager.GetString("UserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование.
        /// </summary>
        public static string UserRole_Name {
            get {
                return ResourceManager.GetString("UserRole.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование страницы по умолчанию.
        /// </summary>
        public static string UserRole_PageInstance_Name {
            get {
                return ResourceManager.GetString("UserRole.PageInstance.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на URL страницы по умолчанию.
        /// </summary>
        public static string UserRole_PageInstance_URL {
            get {
                return ResourceManager.GetString("UserRole.PageInstance.URL", resourceCulture);
            }
        }
    }
}
