//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, подтвердите выполнение действия!.
        /// </summary>
        internal static string ActionConfirmation {
            get {
                return ResourceManager.GetString("ActionConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действия.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администрирование.
        /// </summary>
        internal static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет об отмененных заказах.
        /// </summary>
        internal static string CanceledOrdersReport {
            get {
                return ResourceManager.GetString("CanceledOrdersReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет об остатках ДС.
        /// </summary>
        internal static string CashRemainsReport {
            get {
                return ResourceManager.GetString("CashRemainsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Корректировка.
        /// </summary>
        internal static string Correction {
            get {
                return ResourceManager.GetString("Correction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет о проведённы сделках.
        /// </summary>
        internal static string DealReport {
            get {
                return ResourceManager.GetString("DealReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эл. почта.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Журнал событий.
        /// </summary>
        internal static string EventJournal {
            get {
                return ResourceManager.GetString("EventJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обмен.
        /// </summary>
        internal static string Exchange {
            get {
                return ResourceManager.GetString("Exchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ид.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инвентаризация.
        /// </summary>
        internal static string Inventarisation {
            get {
                return ResourceManager.GetString("Inventarisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет о соответсвии ДС.
        /// </summary>
        internal static string InventarisationReport {
            get {
                return ResourceManager.GetString("InventarisationReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        internal static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя или пароль указаны неверно!.
        /// </summary>
        internal static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход выполнен.
        /// </summary>
        internal static string LoginSuccessfull {
            get {
                return ResourceManager.GetString("LoginSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход в систему.
        /// </summary>
        internal static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройка меню.
        /// </summary>
        internal static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кассовые операции.
        /// </summary>
        internal static string MoneyTransfer {
            get {
                return ResourceManager.GetString("MoneyTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Система мониторинга.
        /// </summary>
        internal static string MonitoringSystem {
            get {
                return ResourceManager.GetString("MonitoringSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оператор.
        /// </summary>
        internal static string Operator {
            get {
                return ResourceManager.GetString("Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Смена пароля.
        /// </summary>
        internal static string PasswordChanging {
            get {
                return ResourceManager.GetString("PasswordChanging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер телефона.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет о прибыли.
        /// </summary>
        internal static string ProfitReport {
            get {
                return ResourceManager.GetString("ProfitReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчеты.
        /// </summary>
        internal static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Менеджер ролей.
        /// </summary>
        internal static string RoleManager {
            get {
                return ResourceManager.GetString("RoleManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка системы.
        /// </summary>
        internal static string SystemLoading {
            get {
                return ResourceManager.GetString("SystemLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки системы.
        /// </summary>
        internal static string SystemSettings {
            get {
                return ResourceManager.GetString("SystemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание пользователя.
        /// </summary>
        internal static string UserCreating {
            get {
                return ResourceManager.GetString("UserCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инициалы.
        /// </summary>
        internal static string UserInitials {
            get {
                return ResourceManager.GetString("UserInitials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Менеджер пользователей.
        /// </summary>
        internal static string UserManager {
            get {
                return ResourceManager.GetString("UserManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль пользователя.
        /// </summary>
        internal static string UserProfile {
            get {
                return ResourceManager.GetString("UserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес.
        /// </summary>
        internal static string User_Email {
            get {
                return ResourceManager.GetString("User.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин.
        /// </summary>
        internal static string User_UserName {
            get {
                return ResourceManager.GetString("User.UserName", resourceCulture);
            }
        }
    }
}
